name: CI

on:
  workflow_call:

jobs:
  setup:
    name: Setup CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # nessesary to get version history
      - name: Get version
        id: version
        uses: paulhatch/semantic-version@v5.0.0-alpha2
        with:
          search_commit_body: true
      - name: get version of file
        id: version_file
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "project.json"
          prop_path: "version"
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: get enviroments from file
        id: environment_file
        run: |
          echo "::set-output name=prop::$(pio project config --json-output | jq -cr '.[0][1][0][1]')"
      - name: Print variables
        run: |
          echo environments: ${{ steps.environment_file.outputs.prop }}
          echo version_tag: ${{ steps.version.outputs.version_tag }}
          echo version: ${{ steps.version.outputs.version }}
          echo up_version: ${{ steps.version.outputs.version != steps.version_file.outputs.prop}}
          echo pullrequest: ${{github.event_name == 'pull_request'}}
          echo pullrequest_end: ${{github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref =='main'}}
    outputs:
      environments: ${{ steps.environment_file.outputs.prop }}
      version_tag: ${{ steps.version.outputs.version_tag }}
      version: ${{ steps.version.outputs.version }}
      up_version: ${{ steps.version.outputs.version != steps.version_file.outputs.prop}}
      pullrequest: ${{github.event_name == 'pull_request'}}
      pullrequest_end: ${{github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref =='main'}}

  up_version:
    if: ${{ needs.setup.outputs.up_version == 'true' }}
    name: Up Version in project file
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: echo ${{needs.setup.outputs.up_version}}
      - uses: actions/checkout@v4
      - name: Modify project.json
        uses: maxgfr/actions-change-json@main
        with:
          key: "version"
          value: "${{ needs.setup.outputs.version }}"
          path: project.json
          commit: true

  test:
    if: ${{ needs.setup.outputs.up_version == 'false' && needs.setup.outputs.pullrequest == 'true'}}
    name: Test Builds
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v4
      - name: Modify project.json
        if: ${{needs.setup.outputs.up_version}}
        uses: maxgfr/actions-change-json@main
        with:
          key: "version"
          value: "${{ needs.setup.outputs.version }}"
          path: project.json
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Define Softwareversion
        run: export PLATFORMIO_BUILD_FLAGS="-D SW_VERSION=${{ needs.setup.outputs.version }}"
      - name: Run PlatformIO Test
        run: pio test

  build:
    if: ${{ needs.setup.outputs.pullrequest_end == 'true'}}
    name: Build Project
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v4
      - name: Modify project.json
        if: ${{needs.setup.outputs.up_version}}
        uses: maxgfr/actions-change-json@main
        with:
          key: "version"
          value: "${{ needs.setup.outputs.version }}"
          path: project.json
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Remove not used Files
        continue-on-error: true
        run: |
          rm platformio.ini
          rm src/main.cpp

      - name: build release folder
        run: |
          pio package pack -o ${{ github.event.repository.name }}.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: Archive
          path: |
            ${{ github.event.repository.name }}.tar.gz
          if-no-files-found: error

  release:
    if: ${{ needs.setup.outputs.pullrequest_end == 'true'}}
    name: Create Release
    runs-on: ubuntu-latest
    needs: [setup, build]
    steps:
      - uses: actions/download-artifact@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.setup.outputs.version_tag }}
          generate_release_notes: true
          files: |
            Archive/${{ github.event.repository.name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
