name: CI

on:
  workflow_call:

jobs:
  setup:
    name: Setup CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # nessesary to get version history
      - name: Get version
        id: version
        uses: paulhatch/semantic-version@v5.0.0-alpha2
        with:
          search_commit_body: true
          # branch: origin/main
      - name: get version of file
        id: version_file
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "library.json"
          prop_path: "version"
      - name: Print variables
        run: |
          echo version_tag: ${{ steps.version.outputs.version_tag }}
          echo version: ${{ steps.version.outputs.version }}
          echo version_file: ${{ steps.version_file.outputs.prop }}
          echo version_file_tag: v${{ steps.version_file.outputs.prop }}
          echo up_version: ${{ steps.version.outputs.version != steps.version_file.outputs.prop}}
          echo pullrequest: ${{github.event_name == 'pull_request'}}
          echo pullrequest_end: ${{github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref =='main'}}
    outputs:
      version_tag: ${{ steps.version.outputs.version_tag }}
      version: ${{ steps.version.outputs.version }}
      version_file: ${{ steps.version_file.outputs.prop }}
      version_file_tag: v${{ steps.version_file.outputs.prop }}
      up_version: ${{ steps.version.outputs.version != steps.version_file.outputs.prop}}
      pullrequest: ${{github.event_name == 'pull_request'}}
      pullrequest_end: ${{github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref =='main'}}

  up_version:
    name: Up Version in lib file
    runs-on: ubuntu-latest
    needs: [setup]
    if: ${{needs.setup.outputs.up_version == 'true'}}
    steps:
      - run: echo ${{needs.setup.outputs.up_version}}
      - uses: actions/checkout@v2
      - name: Modify library.json
        uses: maxgfr/actions-change-json@main
        with:
          key: "version"
          value: "${{ needs.setup.outputs.version }}"
          path: library.json
          commit: true
