name: CI

on:
  workflow_call:
    inputs:
      platformioDevVersion:
        description: "Should the Platformio Develperversion be used?"
        default: false
        required: false
        type: boolean

jobs:
  setup:
    name: Setup CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # nessesary to get version history
      - name: Get version
        id: version
        uses: paulhatch/semantic-version@v5.0.0-alpha2
        with:
          search_commit_body: true
          # branch: origin/main
      - name: get version of file
        id: version_file
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "library.json"
          prop_path: "version"
      - name: Print variables
        run: |
          echo version_tag: ${{ steps.version.outputs.version_tag }}
          echo version: ${{ steps.version.outputs.version }}
          echo version_file: ${{ steps.version_file.outputs.prop }}
          echo version_file_tag: v${{ steps.version_file.outputs.prop }}
          echo up_version: ${{ steps.version.outputs.version != steps.version_file.outputs.prop}}
          echo pullrequest: ${{github.event_name == 'pull_request'}}
          echo pullrequest_end: ${{github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref =='main'}}
    outputs:
      version_tag: ${{ steps.version.outputs.version_tag }}
      version: ${{ steps.version.outputs.version }}
      version_file: ${{ steps.version_file.outputs.prop }}
      version_file_tag: v${{ steps.version_file.outputs.prop }}
      up_version: ${{ steps.version.outputs.version != steps.version_file.outputs.prop}}
      pullrequest: ${{github.event_name == 'pull_request'}}
      pullrequest_end: ${{github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref =='main'}}

  up_version:
    name: Up Version in lib file
    runs-on: ubuntu-latest
    needs: [setup]
    if: ${{needs.setup.outputs.up_version == 'true'}}
    steps:
      - run: echo ${{needs.setup.outputs.up_version}}
      - uses: actions/checkout@v2
      - name: Modify library.json
        uses: maxgfr/actions-change-json@main
        with:
          key: "version"
          value: "${{ needs.setup.outputs.version }}"
          path: library.json
          commit: true

  test:
    name: Test Builds
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - if: needs.setup.outputs.up_version  == 'true' || needs.setup.outputs.pullrequest  == 'false'
        run: |
          echo "::error file=library.json::Version not correct"
          exit 1
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Run PlatformIO Test
        run: pio test --without-uploading
      - name: Validate lib json
        run: pio package pack

  build:
    name: Build Lib
    runs-on: ubuntu-latest
    needs: [setup]
    if: ${{needs.setup.outputs.pullrequest_end == 'true'}}
    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: build release folder
        run: |
          pio package pack -o ${{ github.event.repository.name }}.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: Archive
          path: |
            ${{ github.event.repository.name }}.tar.gz
          if-no-files-found: error

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [setup, test, build]
    if: ${{needs.setup.outputs.pullrequest_end == 'true'}}
    steps:
      - uses: actions/download-artifact@v2
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.setup.outputs.version_file_tag }}
          generate_release_notes: true
          files: |
            ${{ github.event.repository.name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
